### PR TITLE
Storage get count

### PR DESCRIPTION
**Pull request by YohanesSenbeto**
Review and commit

### CODE REVIEW

**Review by eyobsis — APPROVED** [review]
it is all good

**Comment by eyobsis** [comment]
it is all good

**Comment by YohanesSenbeto** [comment]
mege it

**Comment by eyobsis** [comment]
it is all good

**Review by eyobsis — APPROVED** [review]
it all good again

**Review by eyobsis — APPROVED** [review]

**Comment by eyobsis** [comment]
good

**Review by eyobsis — APPROVED** [review]
all good

**Pull request merged**
